services:
  fastapi-app:
    build: .
    container_name: iot-fastapi-app
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus
    container_name: iot-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: iot-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana


  postgres:
    image: postgres:16
    container_name: iot-postgres
    environment:
      POSTGRES_DB: iotdb
      POSTGRES_USER: iotuser
      POSTGRES_PASSWORD: iotpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-storage:/var/lib/postgresql/data

volumes:
  grafana-storage:
  postgres-storage: